### ISSUE TITLE
Building wheel for simpleaudio (setup.py) ... error   ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by safebaseline** [3xp10it/xwaf#22]
Building wheel for simpleaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sg1cgxxg/simpleaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sg1cgxxg/simpleaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9tpzno7b                                                                                                                                 
       cwd: /tmp/pip-install-sg1cgxxg/simpleaudio/                                                                                    
  Complete output (25 lines):                                                                                                         
  running bdist_wheel                                                                                                                 
  running build                                                                                                                       
  running build_py                                                                                                                    
  creating build                                                                                                                      
  creating build/lib.linux-x86_64-3.8                                                                                                 
  creating build/lib.linux-x86_64-3.8/simpleaudio                                                                                     
  copying simpleaudio/__init__.py -> build/lib.linux-x86_64-3.8/simpleaudio                                                           
  copying simpleaudio/shiny.py -> build/lib.linux-x86_64-3.8/simpleaudio                                                              
  copying simpleaudio/functionchecks.py -> build/lib.linux-x86_64-3.8/simpleaudio                                                     
  creating build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                                                          
  copying simpleaudio/test_audio/c.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                           
  copying simpleaudio/test_audio/e.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                           
  copying simpleaudio/test_audio/g.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                           
  copying simpleaudio/test_audio/left_right.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                  
  copying simpleaudio/test_audio/notes_2_16_44.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio                               
  running build_ext                                                                                                                   
  building 'simpleaudio._simpleaudio' extension                                                                                       
  creating build/temp.linux-x86_64-3.8                                                                                                
  creating build/temp.linux-x86_64-3.8/c_src                                                                                          
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DDEBUG=0 -I/usr/include/python3.8 -c c_src/simpleaudio_alsa.c -o build/temp.linux-x86_64-3.8/c_src/simpleaudio_alsa.o             
  c_src/simpleaudio_alsa.c:8:10: fatal error: alsa/asoundlib.h: No such file or directory                                             
      8 | #include <alsa/asoundlib.h>                                                                                                 
        |          ^~~~~~~~~~~~~~~~~~                                                                                                 
  compilation terminated.                                                                                                             
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                                     
  ----------------------------------------                                                                                            
  ERROR: Failed building wheel for simpleaudio
  Running setup.py clean for simpleaudio
Successfully built exp10it wget
Failed to build simpleaudio
Installing collected packages: simpleaudio, beepy, wget, exp10it
    Running setup.py install for simpleaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sg1cgxxg/simpleaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sg1cgxxg/simpleaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6db7ucgv/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/simpleaudio
         cwd: /tmp/pip-install-sg1cgxxg/simpleaudio/                                                                                  
    Complete output (25 lines):                                                                                                       
    running install                                                                                                                   
    running build                                                                                                                     
    running build_py                                                                                                                  
    creating build                                                                                                                    
    creating build/lib.linux-x86_64-3.8                                                                                               
    creating build/lib.linux-x86_64-3.8/simpleaudio                                                                                   
    copying simpleaudio/__init__.py -> build/lib.linux-x86_64-3.8/simpleaudio                                                         
    copying simpleaudio/shiny.py -> build/lib.linux-x86_64-3.8/simpleaudio                                                            
    copying simpleaudio/functionchecks.py -> build/lib.linux-x86_64-3.8/simpleaudio                                                   
    creating build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                                                        
    copying simpleaudio/test_audio/c.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio                                         
    copying simpleaudio/test_audio/e.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio

**Comment by 3xp10it** [comment]
`pip3 install simpleaudio`

**Comment by feixiangdao** [comment]
先安装这个：sudo apt-get install libasound2-dev

**Comment by ab2gbl** [comment]
> 先安装这个：sudo apt-get install libasound2-dev

thanks bro
