### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by 98Kstar** [3xp10it/xwaf#24]
大佬现在我在新的parrort系统跟kali系统上安装您这个脚本，安装simpleaudio这个模块都是报错的。
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hanj4j_z/simpleaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hanj4j_z/simpleaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-blsbwlcj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/fuckduck/.local/include/python3.8/simpleaudio
         cwd: /tmp/pip-install-hanj4j_z/simpleaudio/
    Complete output (25 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/simpleaudio
    copying simpleaudio/__init__.py -> build/lib.linux-x86_64-3.8/simpleaudio
    copying simpleaudio/shiny.py -> build/lib.linux-x86_64-3.8/simpleaudio
    copying simpleaudio/functionchecks.py -> build/lib.linux-x86_64-3.8/simpleaudio
    creating build/lib.linux-x86_64-3.8/simpleaudio/test_audio
    copying simpleaudio/test_audio/c.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio
    copying simpleaudio/test_audio/e.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio
    copying simpleaudio/test_audio/g.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio
    copying simpleaudio/test_audio/left_right.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio
    copying simpleaudio/test_audio/notes_2_16_44.wav -> build/lib.linux-x86_64-3.8/simpleaudio/test_audio
    running build_ext
    building 'simpleaudio._simpleaudio' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/c_src
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DDEBUG=0 -I/usr/include/python3.8 -c c_src/simpleaudio_alsa.c -o build/temp.linux-x86_64-3.8/c_src/simpleaudio_alsa.o
    c_src/simpleaudio_alsa.c:8:10: fatal error: alsa/asoundlib.h: No such file or directory
        8 | #include <alsa/asoundlib.h>
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hanj4j_z/simpleaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hanj4j_z/simpleaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-blsbwlcj/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/fuckduck/.local/include/python3.8/simpleaudio Check the logs for full command output.

**Comment by feixiangdao** [comment]
sudo apt-get install libasound2-dev

**Comment by ilovecode2018** [comment]
equirement already up-to-date: exp10it in /usr/local/lib/python3.8/dist-packages (2.7.71)
Requirement already satisfied, skipping upgrade: bs4 in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (0.0.1)
Requirement already satisfied, skipping upgrade: selenium in /usr/lib/python3/dist-packages (from exp10it) (4.0.0a1)
Requirement already satisfied, skipping upgrade: pycrypto in /usr/lib/python3/dist-packages (from exp10it) (2.6.1)
Requirement already satisfied, skipping upgrade: colorama in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (0.3.9)
Requirement already satisfied, skipping upgrade: pyperclip in /usr/lib/python3/dist-packages (from exp10it) (1.8.0)
Requirement already satisfied, skipping upgrade: mechanicalsoup in /usr/local/lib/python3.8/dist-packages (from exp10it) (1.0.0)
Requirement already satisfied, skipping upgrade: requests in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (2.24.0)
Requirement already satisfied, skipping upgrade: html2text in /usr/lib/python3/dist-packages (from exp10it) (2020.1.16)
Requirement already satisfied, skipping upgrade: beepy in /usr/local/lib/python3.8/dist-packages (from exp10it) (1.0.7)
Requirement already satisfied, skipping upgrade: wget in /usr/local/lib/python3.8/dist-packages (from exp10it) (3.2)
Requirement already satisfied, skipping upgrade: chardet in /usr/lib/python3/dist-packages (from exp10it) (3.0.4)
Requirement already satisfied, skipping upgrade: pymysql in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (0.9.2)
Requirement already satisfied, skipping upgrade: configparser in /usr/local/lib/python3.8/dist-packages (from exp10it) (5.0.1)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /home/kali/.local/lib/python3.8/site-packages (from bs4->exp10it) (4.6.0)
Requirement already satisfied, skipping upgrade: six>=1.4 in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (1.15.0)
Requirement already satisfied, skipping upgrade: lxml in /home/kali/.local/lib/python3.8/site-packages (from mechanicalsoup->exp10it) (4.6.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/kali/.local/lib/python3.8/site-packages (from requests->exp10it) (2017.4.17)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/kali/.local/lib/python3.8/site-packages (from requests->exp10it) (1.24.2)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/kali/.local/lib/python3.8/site-packages (from requests->exp10it) (2.5)
Requirement already satisfied, skipping upgrade: simpleaudio in /usr/local/lib/python3.8/dist-packages (from beepy->exp10it) (1.0.4)
Requirement already satisfied, skipping upgrade: cryptography in /usr/lib/python3/dist-packages (from pymysql->exp10it) (3.2.1)
Traceback (most recent call last):
  File "/home/kali/xwaf/xwaf.py", line 2843, in <module>
    Program()
  File "/home/kali/xwaf/xwaf.py", line 33, in __init__
    self.selfUpdate()
  File "/home/kali/xwaf/xwaf.py", line 178, in selfUpdate
    latestVersion=getVersion("/tmp/xwaf.py")
  File "/home/kali/xwaf/xwaf.py", line 173, in getVersion
    latestVersion=re.search(r"self\.currentVersion\s*=\s*(.*)",content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ilovecode2018** [comment]
> equirement already up-to-date: exp10it in /usr/local/lib/python3.8/dist-packages (2.7.71)
> Requirement already satisfied, skipping upgrade: bs4 in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (0.0.1)
> Requirement already satisfied, skipping upgrade: selenium in /usr/lib/python3/dist-packages (from exp10it) (4.0.0a1)
> Requirement already satisfied, skipping upgrade: pycrypto in /usr/lib/python3/dist-packages (from exp10it) (2.6.1)
> Requirement already satisfied, skipping upgrade: colorama in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (0.3.9)
> Requirement already satisfied, skipping upgrade: pyperclip in /usr/lib/python3/dist-packages (from exp10it) (1.8.0)
> Requirement already satisfied, skipping upgrade: mechanicalsoup in /usr/local/lib/python3.8/dist-packages (from exp10it) (1.0.0)
> Requirement already satisfied, skipping upgrade: requests in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (2.24.0)
> Requirement already satisfied, skipping upgrade: html2text in /usr/lib/python3/dist-packages (from exp10it) (2020.1.16)
> Requirement already satisfied, skipping upgrade: beepy in /usr/local/lib/python3.8/dist-packages (from exp10it) (1.0.7)
> Requirement already satisfied, skipping upgrade: wget in /usr/local/lib/python3.8/dist-packages (from exp10it) (3.2)
> Requirement already satisfied, skipping upgrade: chardet in /usr/lib/python3/dist-packages (from exp10it) (3.0.4)
> Requirement already satisfied, skipping upgrade: pymysql in /home/kali/.local/lib/python3.8/site-packages (from exp10it) (0.9.2)
> Requirement already satisfied, skipping upgrade: configparser in /usr/local/lib/python3.8/dist-packages (from exp10it) (5.0.1)
> Requirement already satisfied, skipping upgrade: beautifulsoup4 in /home/kali/.local/lib/python3.8/site-packages (from bs4->exp10it) (4.6.0)
> Requirement already satisfied, skipping upgrade: six>=1.4 in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (1.15.0)
> Requirement already satisfied, skipping upgrade: lxml in /home/kali/.local/lib/python3.8/site-packages (from mechanicalsoup->exp10it) (4.6.1)
> Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/kali/.local/lib/python3.8/site-packages (from requests->exp10it) (2017.4.17)
> Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/kali/.local/lib/python3.8/site-packages (from requests->exp10it) (1.24.2)
> Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/kali/.local/lib/python3.8/site-packages (from requests->exp10it) (2.5)
> Requirement already satisfied, skipping upgrade: simpleaudio in /usr/local/lib/python3.8/dist-packages (from beepy->exp10it) (1.0.4)
> Requirement already satisfied, skipping upgrade: cryptography in /usr/lib/python3/dist-packages (from pymysql->exp10it) (3.2.1)
> Traceback (most recent call last):
> File "/home/kali/xwaf/xwaf.py", line 2843, in
> Program()
> File "/home/kali/xwaf/xwaf.py", line 33, in **init**
> self.selfUpdate()
> File "/home/kali/xwaf/xwaf.py", line 178, in selfUpdate
> latestVersion=getVersion("/tmp/xwaf.py")
> File "/home/kali/xwaf/xwaf.py", line 173, in getVersion
> latestVersion=re.search(r"self.currentVersion\s*=\s*(.*)",content).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

注释掉33行的自动 更新就可以了。

**Comment by 3xp10it** [comment]
@98Kstar 试试新版本,应该解决了这个问题.
