### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by qszx** [3xp10it/xwaf#25]
1 ⨯
Requirement already up-to-date: exp10it in /home/oo/.local/lib/python3.8/site-packages (2.7.71)
Requirement already satisfied, skipping upgrade: colorama in /usr/lib/python3/dist-packages (from exp10it) (0.4.3)
Requirement already satisfied, skipping upgrade: selenium in /usr/lib/python3/dist-packages (from exp10it) (4.0.0a1)
Requirement already satisfied, skipping upgrade: html2text in /usr/lib/python3/dist-packages (from exp10it) (2020.1.16)
Requirement already satisfied, skipping upgrade: configparser in /home/oo/.local/lib/python3.8/site-packages (from exp10it) (5.0.1)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from exp10it) (2.24.0)
Requirement already satisfied, skipping upgrade: mechanicalsoup in /home/oo/.local/lib/python3.8/site-packages (from exp10it) (0.12.0)
Requirement already satisfied, skipping upgrade: beepy in /home/oo/.local/lib/python3.8/site-packages (from exp10it) (1.0.7)
Requirement already satisfied, skipping upgrade: pymysql in /home/oo/.local/lib/python3.8/site-packages (from exp10it) (0.10.1)
Requirement already satisfied, skipping upgrade: chardet in /usr/lib/python3/dist-packages (from exp10it) (3.0.4)
Requirement already satisfied, skipping upgrade: bs4 in /home/oo/.local/lib/python3.8/site-packages (from exp10it) (0.0.1)
Requirement already satisfied, skipping upgrade: pyperclip in /usr/lib/python3/dist-packages (from exp10it) (1.8.0)
Requirement already satisfied, skipping upgrade: wget in /home/oo/.local/lib/python3.8/site-packages (from exp10it) (3.2)
Requirement already satisfied, skipping upgrade: pycrypto in /usr/lib/python3/dist-packages (from exp10it) (2.6.1)
Requirement already satisfied, skipping upgrade: lxml in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (4.6.1)
Requirement already satisfied, skipping upgrade: six>=1.4 in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (1.15.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.4 in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (4.9.3)
Requirement already satisfied, skipping upgrade: simpleaudio in /home/oo/.local/lib/python3.8/site-packages (from beepy->exp10it) (1.0.4)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4>=4.4->mechanicalsoup->exp10it) (2.0.1)
+-+-+-+-+
|x|w|a|f|
+-+-+-+-+
currentVersion:1.19
Do you want to use random proxy from the Internet on each different sqlmap command to anti blocked by waf for your mass requests? [N|y]
4 seconds left...please input your chioce:>y
you choosed y
3 seconds left...please input your chioce:>Traceback (most recent call last):
  File "xwaf.py", line 2843, in <module>
    Program()
  File "xwaf.py", line 76, in __init__
    self.check_DB_type_from_script(each_script)
  File "xwaf.py", line 420, in check_DB_type_from_script
    with open('/usr/share/sqlmap/tamper/' + script_name, 'r+',errors='ignore') as f:
PermissionError: [Errno 13] Permission denied: '/usr/share/sqlmap/tamper/space2mysqlblank.py'

**Comment by ilovecode2018** [comment]
sudo python3 xwaf.py -u 这样可以解决权限问题
