### ISSUE TITLE
这是什么问题，怎么解决呢？

### ISSUE THREAD

**Issue by 1683728221** [3xp10it/xwaf#26]
[正在执行:python2 /usr/share/sqlmap/sqlmap.py -u "https://xxxxxx.com/activityScratchLog?activityId=" --batch --risk "3" -v "3" --threadsh: python2: command not foundl "https://xxxxxx.com" --safe-freq "1" --level "5" --smart]
touch: cannot touch ‘/root/.sqlmap/output/xxxxxx.com/config_file.ini’: No such file or directory
Traceback (most recent call last):
  File "xwaf.py", line 2843, in <module>
    Program()
  File "xwaf.py", line 107, in __init__
    update_config_file_key_value(self.log_config_file, 'default', 'finished_command_list', [])
  File "/usr/local/python3/lib/python3.7/site-packages/exp10it.py", line 2939, in update_config_file_key_value
    with open(file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.sqlmap/output/xxxxxx.com/config_file.ini'

**Comment by 3xp10it** [comment]
需要用python3执行,你用的系统是?

**Comment by 3xp10it** [comment]
可将33行注释后再运行，如下：
`#self.selfUpdate()`
