### ISSUE TITLE
xwaf针对SQLmap更新之后无法正常使用

### ISSUE THREAD

**Issue by QQ704568679** [3xp10it/xwaf#29]
作者你好，原始版的SQLmap的日志存放位置和新版的SQLmap存储位置不同导致你的xwaf无法直接使用，并且会一直提示：无法创建 '/root/.sqlmap/output/nflsfc.com.cn/config_file.ini': 没有那个文件或目录，所以你能更新下存储位置的这段代码吗？以及你代码当中链接位置的那个xwaf脚本的代码一并更新下可以吗

**Comment by 3xp10it** [comment]
已完成更新
